version: '3.4'

services:
  nutrientservice.api:
    image: ${DOCKER_REGISTRY-}nutrientserviceapi
    build:
      context: .
      dockerfile: NutrientService\NutrientService.API\Dockerfile


  mongodb_container:
    image: mongo:latest
    container_name: nutrient-db
    ports:
      - 27017:27017
      