version: '3.4'

services:

  traefik:
    image: "traefik:v2.6"
    container_name: "traefik"
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--providers.docker.network=web"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    labels:
      - "traefik.http.routers.api.rule=Host(`traefik.localhost`)"
      - "traefik.http.routers.api.service=api@internal"
    networks:
      - web


  nutrientservice.api:
    image: ${DOCKER_REGISTRY-}nutrientserviceapi
    build:
      context: .
      dockerfile: NutrientService\NutrientService.API\Dockerfile
    ports:
      - 81:80
      #- 60087:443
    networks:
        - backend
        - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nutrients.rule=Host(`localhost`) && PathPrefix(`/api/nutrient`)"
      - "traefik.http.routers.nutrients.entrypoints=web"


  diaryservice.api:
    image: ${DOCKER_REGISTRY-}diaryserviceapi
    build:
      context: .
      dockerfile: DiaryService\DiaryService.API\Dockerfile
    ports:
      - 82:80
      #- 60088:443
    networks:
        - backend
        - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.diary.rule=Host(`localhost`) && PathPrefix(`/api/diaries`)"
      - "traefik.http.routers.diary.entrypoints=web"



  mongodb_container:
    image: mongo:5.0
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
       - shared_database:/usr/local/mongo
    networks:
        - backend
    #environment:
    #    - MONGO_INITDB_ROOT_USERNAME=root 
    #    - MONGO_INITDB_ROOT_PASSWORD=root 
      

volumes:
    shared_database:
    #dynamic.yaml:
    docker.sock:
    #letsencrypt:


networks:
  backend:  
    external: false
    name: backend
  web:
    external: false
    name: web
  
  

