version: '3.4'

services:
  nutrientservice.api:
    image: ${DOCKER_REGISTRY-}nutrientserviceapi
    build:
      context: .
      dockerfile: NutrientService\NutrientService.API\Dockerfile
    networks:
        - nutrient-network


  diaryservice.api:
    image: ${DOCKER_REGISTRY-}diaryserviceapi
    build:
      context: .
      dockerfile: DiaryService\DiaryService.API\Dockerfile
    networks:
        - diary-network


  mongodb_container:
    image: mongo:5.0
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
       - shared_database:/usr/local/mongo
    networks:
        - nutrient-network
        - diary-network
    #environment:
    #    - MONGO_INITDB_ROOT_USERNAME=root 
    #    - MONGO_INITDB_ROOT_PASSWORD=root 
      

volumes:
    shared_database:

networks:
  nutrient-network:
  diary-network:

